name: Translate, build and deploy Sphinx docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Set-up
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx alabaster rst2pdf sphinx-intl polib requests svglib

    # Spanish
    - name: Build HTML
      run: |
        cd docs
        sphinx-build -b html . _build/es

    - name: Convert RST to PDF
      run: |
        cd docs
        mkdir -p _build/es/pdf
        for file in *.rst; do
          rst2pdf "$file" -o "_build/es/pdf/${file%.rst}.pdf" -s pdfstyle.json
        done
        cp _build/es/pdf/*.pdf _build/es/

    # English
    - name: Extract translation templates
      run: |
        cd docs
        sphinx-build -b gettext . _build/gettext

    - name: Update .po files for EN
      run: |
        cd docs
        sphinx-intl update -p _build/gettext -l en

    - name: Translate PO files
      env:
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: |
        python translate_po.py

    - name: Build HTML
      run: |
        cd docs
        sphinx-build -b html -D language=en . _build/en

    - name: Replace en/ with es/ in English HTML
      run: |
        cd docs/_build/en
        find . -type f -name "*.html" -exec sed -i 's|https://PumukyDev.github.io/portswigger-websecurity-academy/en/|https://PumukyDev.github.io/portswigger-websecurity-academy/es/|g' {} +

    - name: Convert RST to PDF
      run: |
        cd docs
        mkdir -p _build/en/pdf
        for file in *.rst; do
          rst2pdf "$file" -o "_build/en/pdf/${file%.rst}.pdf" -s pdfstyle.json
        done
        cp _build/en/pdf/*.pdf _build/en/

    # Publish docs
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        publish_branch: gh-pages
