name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme rst2pdf

    - name: Build HTML documentation
      run: |
        cd docs
        sphinx-build -b html . _build/html

    - name: Convert RST to PDF
      run: |
        cd docs
        mkdir -p _build/pdf
        for file in *.rst; do
          rst2pdf "$file" -o "_build/pdf/${file%.rst}.pdf" -s pdfstyle.json
        done
        cp _build/pdf/*.pdf _build/html/

    - name: Upload HTML documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation-html
        path: docs/_build/html

    - name: Upload PDF documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation-pdf
        path: docs/_build/pdf/*.pdf

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        publish_branch: gh-pages